# Generated by Django 5.1.2 on 2025-05-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookieapp', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tenent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.tenant'),
        ),
    ]
