# Generated by Django 5.1.2 on 2025-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookieapp', '0002_account_tenent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='ABC', max_length=200),
        ),
    ]
