# Generated by Django 5.1.2 on 2025-07-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookieapp', '0004_account_address_account_country_code_account_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country_code',
            field=models.CharField(default='+91', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=100)),
                ('for_delivery', models.BooleanField(default=True)),
                ('for_invoice', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
