# Generated by Django 5.1.2 on 2025-07-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookieapp', '0005_alter_account_country_code_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
