# Generated by Django 5.1.2 on 2025-07-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carousel_category_sort_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameter_value', models.TextField()),
            ],
        ),
    ]
