# Generated by Django 5.1.2 on 2025-05-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=60)),
                ('time_slot', models.CharField(max_length=70)),
                ('is_delivery', models.BooleanField(default=False)),
                ('building', models.CharField(max_length=70, null=True)),
                ('Street', models.CharField(max_length=70, null=True)),
                ('Zone', models.CharField(max_length=70, null=True)),
                ('location', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('customize', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
                ('productcustomize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.product')),
            ],
        ),
    ]
